version: "3.8"

services: 
  authentication:
    image: 127.0.0.1:5000/authentication
    build: .
    ports: 
      - '8000:8000'
    deploy:
      replicas: 2
  doctor:
    image: 127.0.0.1:5000/doctor
    build: .
    ports: 
      - '8001:8001'
  patient:
    image: 127.0.0.1:5000/patient
    build: .
    ports: 
      - '8002:8002'
  visualizer:
    image: dockersamples/visualizer
    ports: 
      - '8080:8080'
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints: [node.role == manager]